# Generated by Django 5.0 on 2023-12-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_service", "0003_remove_bookingmodel_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingmodel",
            name="payment_id",
            field=models.UUIDField(null=True),
        ),
    ]
