# Generated by Django 5.0 on 2023-12-15 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking_service", "0003_remove_bookingmodel_payment_id"),
        ("payment_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentCustomerModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="booking",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking_service.bookingmodel",
            ),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="client_secret",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="payment_intent_id",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment_service.paymentcustomermodel",
            ),
        ),
    ]
