# Generated by Django 5.0 on 2023-12-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymodel",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
