# Generated by Django 5.0 on 2023-12-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_service", "0002_alter_inventorymodel_is_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorymodel",
            name="is_available",
        ),
        migrations.AddField(
            model_name="inventorymodel",
            name="state",
            field=models.IntegerField(default=1),
        ),
    ]
